# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAccesspagesnonlogin():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_accesspagesnonlogin(self):
    self.driver.get("http://127.0.0.1:5000/login?next=%2F")
    self.driver.set_window_size(550, 680)
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "Take Test").click()
    self.driver.find_element(By.LINK_TEXT, "Results").click()
    self.driver.find_element(By.LINK_TEXT, "Test History").click()
    self.driver.find_element(By.LINK_TEXT, "Authors").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".author_block:nth-child(2) .fa-linkedin-square").click()
    self.vars["win5027"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win5027"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.CSS_SELECTOR, ".author_block:nth-child(2) .fa-envelope-square").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".author_block:nth-child(2) .fa-github").click()
    self.vars["win8730"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win8730"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".author_block:nth-child(3) .fa-linkedin-square").click()
    self.vars["win9725"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win9725"])
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.CSS_SELECTOR, ".author_block:nth-child(3) .fa-envelope-square").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".author_block:nth-child(3) .fa-github").click()
    self.vars["win9662"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win9662"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.driver.switch_to.window(self.vars["win9725"])
    self.driver.close()
  
