"""database

Revision ID: 2b1018212bf2
Revises: 
Create Date: 2020-05-22 16:49:25.624140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b1018212bf2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=256), nullable=True),
    sa.Column('correctAnswer', sa.String(length=64), nullable=True),
    sa.Column('answer2', sa.String(length=64), nullable=True),
    sa.Column('answer3', sa.String(length=64), nullable=True),
    sa.Column('answer4', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_question_body'), 'question', ['body'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('question_set',
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('set_name', sa.String(length=64), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('set_id'),
    sa.UniqueConstraint('set_name')
    )
    op.create_table('Quizzes',
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['question_set.set_id'], ),
    sa.PrimaryKeyConstraint('set_id', 'question_id')
    )
    op.create_table('answer_set',
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('qset_id', sa.Integer(), nullable=True),
    sa.Column('numberCorrect', sa.Integer(), nullable=True),
    sa.Column('numberIncorrect', sa.Integer(), nullable=True),
    sa.Column('score', sa.String(length=4), nullable=True),
    sa.Column('timeOfAttempt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['qset_id'], ['question_set.set_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('set_id')
    )
    op.create_index(op.f('ix_answer_set_timeOfAttempt'), 'answer_set', ['timeOfAttempt'], unique=False)
    op.create_table('user_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('questionId', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=64), nullable=True),
    sa.Column('setID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questionId'], ['question.question_id'], ),
    sa.ForeignKeyConstraint(['setID'], ['question_set.set_id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Answer Sets',
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['user_answers.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['answer_set.set_id'], ),
    sa.PrimaryKeyConstraint('set_id', 'answer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Answer Sets')
    op.drop_table('user_answers')
    op.drop_index(op.f('ix_answer_set_timeOfAttempt'), table_name='answer_set')
    op.drop_table('answer_set')
    op.drop_table('Quizzes')
    op.drop_table('question_set')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_question_body'), table_name='question')
    op.drop_table('question')
    # ### end Alembic commands ###
