"""comb_aset_useratt

Revision ID: 30fe82216e9c
Revises: bd312a11e93e
Create Date: 2020-05-20 16:00:31.898934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30fe82216e9c'
down_revision = 'bd312a11e93e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_set', sa.Column('numberCorrect', sa.Integer(), nullable=True))
    op.add_column('answer_set', sa.Column('numberIncorrect', sa.Integer(), nullable=True))
    op.add_column('answer_set', sa.Column('score', sa.String(length=4), nullable=True))
    op.add_column('answer_set', sa.Column('timeOfAttempt', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_answer_set_timeOfAttempt'), 'answer_set', ['timeOfAttempt'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_set_timeOfAttempt'), table_name='answer_set')
    op.drop_column('answer_set', 'timeOfAttempt')
    op.drop_column('answer_set', 'score')
    op.drop_column('answer_set', 'numberIncorrect')
    op.drop_column('answer_set', 'numberCorrect')
    # ### end Alembic commands ###
