"""added user attempts table

Revision ID: 640456529bde
Revises: 179227b4922c
Create Date: 2020-05-18 23:23:24.052146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640456529bde'
down_revision = '179227b4922c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_attempts',
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('numberCorrect', sa.Integer(), nullable=True),
    sa.Column('numberIncorrect', sa.Integer(), nullable=True),
    sa.Column('score', sa.String(length=4), nullable=True),
    sa.Column('timeOfAttempt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_index(op.f('ix_user_attempts_timeOfAttempt'), 'user_attempts', ['timeOfAttempt'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_attempts_timeOfAttempt'), table_name='user_attempts')
    op.drop_table('user_attempts')
    # ### end Alembic commands ###
