"""added UserAnswers table

Revision ID: 8084bda34c37
Revises: 5d602a6053bf
Create Date: 2020-05-17 20:48:50.864709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8084bda34c37'
down_revision = '5d602a6053bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('questionId', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['questionId'], ['question.question_id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_answers')
    # ### end Alembic commands ###
