"""questions table

Revision ID: f3490d4ea872
Revises: f9a59342f6ea
Create Date: 2020-05-16 10:34:28.104642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3490d4ea872'
down_revision = 'f9a59342f6ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=256), nullable=True),
    sa.Column('choice_1', sa.String(length=64), nullable=True),
    sa.Column('choice_2', sa.String(length=64), nullable=True),
    sa.Column('choice_3', sa.String(length=64), nullable=True),
    sa.Column('choice_4', sa.String(length=64), nullable=True),
    sa.Column('correct_answer', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_question_body'), 'question', ['body'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_body'), table_name='question')
    op.drop_table('question')
    # ### end Alembic commands ###
